steps:
  - name: 'ubuntu'
    args: ['bash', './my-script.sh']
  - name: 'gcr.io/cloud-builders/go'
    args: ['install', './cmd/...']
    env: ['PROJECT_ROOT=github.com/iamsubratp/test-cloud-build/app']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/test-cloud-build', '.']
images: ['gcr.io/$PROJECT_ID/test-cloud-build']